on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'build'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Archive binary
        uses: actions/upload-artifact@v2
        with:
            name: raspb-app
            path: build/raspb-app